// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: articles.sql

package domain

import (
	"context"

	"github.com/google/uuid"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO "article"("title", "body", "description", "slug", "author_id", "status")
  VALUES ($1, $2, $3, $4, $6::uuid, $5)
RETURNING
  id, title, body, description, slug, author_id, status, created_at, updated_at
`

type CreateArticleParams struct {
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	Description *string   `json:"description"`
	Slug        string    `json:"slug"`
	Status      *string   `json:"status"`
	AuthorID    uuid.UUID `json:"authorId"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Body,
		arg.Description,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.Slug,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM
  "article"
WHERE
  "slug" = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteArticle, slug)
	return err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT
  id, title, body, description, slug, author_id, status, created_at, updated_at
FROM
  "article"
WHERE
  "slug" = $1
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.Slug,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT
  id, title, body, description, slug, author_id, status, created_at, updated_at
FROM
  "article"
WHERE
  "status" = 'published'
  AND (
    "title" ILIKE '%' || coalesce($1, '') || '%' OR
    "slug" ILIKE '%' || coalesce($2, '') || '%'
  )
LIMIT coalesce($4::int, 10) OFFSET coalesce($3::int, 0)
`

type ListArticlesParams struct {
	Title  *string `json:"title"`
	Slug   *string `json:"slug"`
	Offset *int32  `json:"offset"`
	Limit  *int32  `json:"limit"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.Title,
		arg.Slug,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Description,
			&i.Slug,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE
  "article"
SET
  "title" = coalesce($1, title),
  "body" = coalesce($2, body),
  "description" = coalesce($3, description),
  "status" = coalesce($4, status)
WHERE
  "slug" = $5
RETURNING
  id, title, body, description, slug, author_id, status, created_at, updated_at
`

type UpdateArticleParams struct {
	Title       *string `json:"title"`
	Body        *string `json:"body"`
	Description *string `json:"description"`
	Status      *string `json:"status"`
	Slug        string  `json:"slug"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.Title,
		arg.Body,
		arg.Description,
		arg.Status,
		arg.Slug,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.Slug,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
