// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: articles.sql

package domain

import (
	"context"

	"github.com/google/uuid"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO "article"("title", "body", "description", "slug", "author_id", "status")
  VALUES ($1, $2, $3, $4, $6::uuid, $5)
RETURNING
  id, title, body, description, slug, author_id, status, created_at, updated_at
`

type CreateArticleParams struct {
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	Description *string   `json:"description"`
	Slug        string    `json:"slug"`
	Status      *string   `json:"status"`
	AuthorID    uuid.UUID `json:"authorId"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Body,
		arg.Description,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.Slug,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
