// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: articles.sql

package domain

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO "article"("title", "body", "description", "slug", "author_id", "status")
  VALUES ($1, $2, $3, $4, $6::uuid, $5)
RETURNING
  id, title, body, description, slug, author_id, status, created_at, updated_at
`

type CreateArticleParams struct {
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	Description *string   `json:"description"`
	Slug        string    `json:"slug"`
	Status      *string   `json:"status"`
	AuthorID    uuid.UUID `json:"authorId"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Body,
		arg.Description,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.Slug,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM
  "article"
WHERE
  "slug" = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteArticle, slug)
	return err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT
  id, title, body, description, slug, author_id, status, created_at, updated_at
FROM
  "article"
WHERE
  "slug" = $1
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.Slug,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT
  id, title, body, description, slug, author_id, status, created_at, updated_at
FROM
  "article"
WHERE
  "status" = 'published'
  AND (
    "title" ILIKE '%' || coalesce($1, '') || '%' OR
    "slug" ILIKE '%' || coalesce($2, '') || '%'
  )
LIMIT coalesce($4::int, 10) OFFSET coalesce($3::int, 0)
`

type ListArticlesParams struct {
	Title  *string `json:"title"`
	Slug   *string `json:"slug"`
	Offset *int32  `json:"offset"`
	Limit  *int32  `json:"limit"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.Title,
		arg.Slug,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Description,
			&i.Slug,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteArticles = `-- name: ListFavoriteArticles :many
SELECT
  id, title, body, description, slug, author_id, status, article.created_at, article.updated_at, user_id, article_id, favorite.created_at, favorite.updated_at
FROM
  "article"
INNER JOIN "favorite" ON "article"."id" = "favorite"."article_id"
WHERE
  "favorite"."user_id" = $1::uuid
LIMIT coalesce($3::int, 10) OFFSET coalesce($2::int, 0)
`

type ListFavoriteArticlesParams struct {
	UserID uuid.UUID `json:"userId"`
	Offset *int32    `json:"offset"`
	Limit  *int32    `json:"limit"`
}

type ListFavoriteArticlesRow struct {
	ID          uuid.UUID        `json:"id"`
	Title       string           `json:"title"`
	Body        string           `json:"body"`
	Description *string          `json:"description"`
	Slug        string           `json:"slug"`
	AuthorID    uuid.UUID        `json:"authorId"`
	Status      *string          `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
	UserID      uuid.UUID        `json:"userId"`
	ArticleID   uuid.UUID        `json:"articleId"`
	CreatedAt_2 pgtype.Timestamp `json:"createdAt2"`
	UpdatedAt_2 pgtype.Timestamp `json:"updatedAt2"`
}

func (q *Queries) ListFavoriteArticles(ctx context.Context, arg ListFavoriteArticlesParams) ([]ListFavoriteArticlesRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteArticles, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoriteArticlesRow{}
	for rows.Next() {
		var i ListFavoriteArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Description,
			&i.Slug,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ArticleID,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishArticle = `-- name: PublishArticle :one
UPDATE
  "article"
SET
  "status" = coalesce($1, status)
WHERE
  "slug" = $2
RETURNING
  id, title, body, description, slug, author_id, status, created_at, updated_at
`

type PublishArticleParams struct {
	Status *string `json:"status"`
	Slug   string  `json:"slug"`
}

func (q *Queries) PublishArticle(ctx context.Context, arg PublishArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, publishArticle, arg.Status, arg.Slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.Slug,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE
  "article"
SET
  "title" = coalesce($1, title),
  "body" = coalesce($2, body),
  "description" = coalesce($3, description)
WHERE
  "slug" = $4
RETURNING
  id, title, body, description, slug, author_id, status, created_at, updated_at
`

type UpdateArticleParams struct {
	Title       *string `json:"title"`
	Body        *string `json:"body"`
	Description *string `json:"description"`
	Slug        string  `json:"slug"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.Title,
		arg.Body,
		arg.Description,
		arg.Slug,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.Slug,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
