// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package domain

import (
	"context"

	"github.com/google/uuid"
)

const addComment = `-- name: AddComment :one
INSERT INTO "comment"("article_id", "author_id", "body")
  VALUES ($1, $2, $3)
RETURNING
  id, article_id, author_id, body, created_at, updated_at
`

type AddCommentParams struct {
	ArticleID uuid.UUID `json:"articleId"`
	AuthorID  uuid.UUID `json:"authorId"`
	Body      string    `json:"body"`
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, addComment, arg.ArticleID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
