// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package domain

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addComment = `-- name: AddComment :one
INSERT INTO "comment"("article_id", "author_id", "body")
  VALUES ($1, $2, $3)
RETURNING
  id, article_id, author_id, body, created_at, updated_at
`

type AddCommentParams struct {
	ArticleID uuid.UUID `json:"articleId"`
	AuthorID  uuid.UUID `json:"authorId"`
	Body      string    `json:"body"`
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, addComment, arg.ArticleID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsForArticleBySlug = `-- name: ListCommentsForArticleBySlug :many
SELECT
  "comment"."id",
  "comment"."body",
  "comment"."created_at",
  "comment"."updated_at",
  "comment"."article_id",
  "comment"."author_id"
FROM
  "comment"
INNER JOIN "article" ON "comment"."article_id" = "article"."id"
WHERE
  "article"."slug" = $1
`

type ListCommentsForArticleBySlugRow struct {
	ID        uuid.UUID        `json:"id"`
	Body      string           `json:"body"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	ArticleID uuid.UUID        `json:"articleId"`
	AuthorID  uuid.UUID        `json:"authorId"`
}

func (q *Queries) ListCommentsForArticleBySlug(ctx context.Context, slug string) ([]ListCommentsForArticleBySlugRow, error) {
	rows, err := q.db.Query(ctx, listCommentsForArticleBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsForArticleBySlugRow{}
	for rows.Next() {
		var i ListCommentsForArticleBySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleID,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
