// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: favorites.sql

package domain

import (
	"context"

	"github.com/google/uuid"
)

const addArticleAsFavorite = `-- name: AddArticleAsFavorite :one
INSERT INTO "favorite" ("user_id", "article_id")
VALUES ($1, $2)
RETURNING user_id, article_id, created_at, updated_at
`

type AddArticleAsFavoriteParams struct {
	UserID    uuid.UUID `json:"userId"`
	ArticleID uuid.UUID `json:"articleId"`
}

func (q *Queries) AddArticleAsFavorite(ctx context.Context, arg AddArticleAsFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, addArticleAsFavorite, arg.UserID, arg.ArticleID)
	var i Favorite
	err := row.Scan(
		&i.UserID,
		&i.ArticleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeArticleAsFavorite = `-- name: RemoveArticleAsFavorite :exec
DELETE FROM "favorite"
WHERE "user_id" = $1 AND "article_id" = $2
`

type RemoveArticleAsFavoriteParams struct {
	UserID    uuid.UUID `json:"userId"`
	ArticleID uuid.UUID `json:"articleId"`
}

func (q *Queries) RemoveArticleAsFavorite(ctx context.Context, arg RemoveArticleAsFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeArticleAsFavorite, arg.UserID, arg.ArticleID)
	return err
}
