// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: follows.sql

package domain

import (
	"context"

	"github.com/google/uuid"
)

const followUser = `-- name: FollowUser :one
INSERT INTO "follow"("following_user_id", "followed_user_id")
  VALUES ($1::uuid, $2::uuid)
RETURNING
  following_user_id, followed_user_id, created_at, updated_at
`

type FollowUserParams struct {
	FollowingUserID uuid.UUID `json:"followingUserId"`
	FollowedUserID  uuid.UUID `json:"followedUserId"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (Follow, error) {
	row := q.db.QueryRow(ctx, followUser, arg.FollowingUserID, arg.FollowedUserID)
	var i Follow
	err := row.Scan(
		&i.FollowingUserID,
		&i.FollowedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM "follow"
WHERE "following_user_id" = $1::uuid
  AND "followed_user_id" = $2::uuid
`

type UnfollowUserParams struct {
	FollowingUserID uuid.UUID `json:"followingUserId"`
	FollowedUserID  uuid.UUID `json:"followedUserId"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowingUserID, arg.FollowedUserID)
	return err
}
