// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package domain

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
	// Content of the article
	Body        string           `json:"body"`
	Description *string          `json:"description"`
	Slug        string           `json:"slug"`
	AuthorID    pgtype.UUID      `json:"authorId"`
	Status      *string          `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type ArticleTag struct {
	ArticleID uuid.UUID `json:"articleId"`
	TagID     uuid.UUID `json:"tagId"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	ArticleID uuid.UUID `json:"articleId"`
	AuthorID  uuid.UUID `json:"authorId"`
	// Content of the comment
	Body      string           `json:"body"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type Favorite struct {
	UserID    uuid.UUID        `json:"userId"`
	ArticleID uuid.UUID        `json:"articleId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type Follow struct {
	FollowingUserID uuid.UUID        `json:"followingUserId"`
	FollowedUserID  uuid.UUID        `json:"followedUserId"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
}

type Tag struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	Bio          *string          `json:"bio"`
	Image        string           `json:"image"`
	PasswordHash string           `json:"passwordHash"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}
